sudo: false
language: node_js
node_js:
# We could enable testing on multiple versions, uncomment to add more.
#- '6'
#- '7'
- '8'
env:
- CACHE_TIMEOUT_SECONDS=5
cache:
  directories:
  - node_modules
addons:
  apt:
    packages:
    - graphicsmagick
services:
- redis-server

